### ISSUE TITLE
gdal missing netcdf support

### ISSUE THREAD

**Issue by jhamman** [conda/conda-recipes#123]
`gdal` can be compiled with netCDF support but the current conda recipe does not include it.  Any chance the recipe could be updated?

**Comment by kpurdon** [comment]
Looks like this has been added in the latest build: https://github.com/conda/conda-recipes/blob/master/gdal/build.sh. Can you test with this and confirm/close this issue?

**Comment by jhamman** [comment]
Looks good.  Thanks.
