### ISSUE TITLE
gdal_merge.py missing from gdal install on windows

### ISSUE THREAD

**Issue by jahfet** [conda/conda-recipes#211]
I am not sure if this is the correct place to report the issue...

When installing gdal through conda install gdal on windows, [gdal_merge.py](http://svn.osgeo.org/gdal/trunk/gdal/swig/python/scripts/gdal_merge.py) is not available in C:\Anaconda\Lib\site-packages\osgeo unlike all the other gdal utilities (gdalwarp, etc)

It appears to be present on linux.

**Comment by rsignell-usgs** [comment]
I also just hit this problem with GDAL on Anaconda 64bit Windows.    

It's interesting that `gdalinfo.exe` and other `.exe` files are present, but not `gdal_merge.py`.    

Other problems with the conda GDAL package for windows are:
* missing `include` directory (which means that trying to build other conda packages like `rasterio` fail)
* missing `share` directory (which means that gdal projection conversion and many other utilities will fail because they cannot load info about projections)

@ilanschnell or @asmeurer , is the problem here that the conda package was converted from a Gohlke binary and these aspects got missed by the automatic conversion process?

**Comment by dharhas** [comment]
hitting the same issue on osx

**Comment by rsignell-usgs** [comment]
@dharhas , it looks like the [gdal conda-recipe](https://github.com/danclewley/conda-recipes/blob/master/gdal/build.sh)  from @danclewley is more complete: at least it is dealing with the `share` packages. 
I think these recipes are what populate the http://binstar.org/osgeo channel packages.

**Comment by ilanschnell** [comment]
Hi Rich,
thanks for pointing out the recipe from @danclewley
<https://github.com/danclewley>, by looking at the info/recipe directory of
these conda on http://binstar.org/osgeo, you can tell that they are indeed
from that recipe.
I'm looking into the missing script files on Windows.

Thanks   Ilan

**Comment by rsignell-usgs** [comment]
@ilanschnell , excellent.  I'm glad you are on the case!

**Comment by ilanschnell** [comment]
Looking at Gohlkes Windows binaries, it seems that the scripts, such as gdal_merge.py are missing.

**Comment by rsignell-usgs** [comment]
@ilanschnell , aha!  So this *was* converted from Gohlke's package.   Hopefully we can work toward getting a CMAKE configuration for gdal so we can more easily build on windows.

**Comment by dharhas** [comment]
Any update this? Just wondering if it is on anyone's radar?

**Comment by ilanschnell** [comment]
I've added the Scripts on Windows, and uploaded new packages to
repo.continuum.io.
The scripts, such as gdal_merge, are simply in the Scripts directory.  Use
"conda update gdal".

**Comment by dharhas** [comment]
I'm getting a DLL error on win32 when trying to import gdal from the python command prompt

'>>> import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rditldp9\AppData\Local\Continuum\Anaconda\lib\site-packages\gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "C:\Users\rditldp9\AppData\Local\Continuum\Anaconda\lib\site-packages\osgeo\__init__.py", line 32, in <module>
    _gdal = swig_import_helper()
  File "C:\Users\rditldp9\AppData\Local\Continuum\Anaconda\lib\site-packages\osgeo\__init__.py", line 28, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: DLL load failed: The specified module could not be found.

**Comment by groutr** [comment]
We are working to build this package from source on all platforms.

**Comment by danclewley** [comment]
The recipe in our fork of the conda repo (https://github.com/danclewley/conda-recipes) works for Windows, Linux and OS X if you want to try this. Binaries for Python 3 are on binstar in the channel osgeo.

**Comment by dharhas** [comment]
Unfortunately the windows binary for python 2.7 are not available in the osgeo channel. Which is my primary need. Currently, I have downgraded to GDAL 1.11.0 in the main channel and converted the rasterio and fiona wheel packages from Christophe Golhke into conda packages for win64. These are available for python 2.7 for win64/linux64 and osx in the erdc channel. This is working for me although not ideal. 

Having gdal/fiona/rasterio built correctly and available cross platform in the main Anaconda channel would be a huge deal for recommending Anaconda to geospatial folks...

**Comment by groutr** [comment]
GDAL is currently be rebuilt for all platforms.

**Comment by jdmcbr** [comment]
Any update on this? It would be great to have all the gdal utilities, and other gdal dependent packages, working well and installable with conda in Windows.

**Comment by groutr** [comment]
The gdal utilities are in the anaconda gdal package named libgdal.
They are located in the Library\bin folder.

**Comment by jdmcbr** [comment]
Before bumping, I had actually tested the latest anaconda gdal/libgdal packages (1.11.2), and ran into the error referenced in https://github.com/ContinuumIO/anaconda-issues/issues/221. I've gotten this error in both Windows 7 and 8.

**Comment by groutr** [comment]
These files are present in the libgdal package:
```
Library/bin/gdal_contour.exe
Library/bin/gdal_grid.exe
Library/bin/gdal_rasterize.exe
Library/bin/gdal_translate.exe
Library/bin/gdaladdo.exe
Library/bin/gdalbuildvrt.exe
Library/bin/gdaldem.exe
Library/bin/gdalenhance.exe
Library/bin/gdalinfo.exe
Library/bin/gdallocationinfo.exe
Library/bin/gdalmanage.exe
Library/bin/gdalserver.exe
Library/bin/gdalsrsinfo.exe
Library/bin/gdaltindex.exe
Library/bin/gdaltransform.exe
Library/bin/gdalwarp.exe
Library/bin/nearblack.exe
Library/bin/ogr2ogr.exe
Library/bin/ogrinfo.exe
Library/bin/ogrlineref.exe
Library/bin/ogrtindex.exe
Library/bin/testepsg.exe
...
Library/data/gcs.csv
```

**Comment by jdmcbr** [comment]
Ah, so they are. Thank you.

**Comment by groutr** [comment]
So I just updated gdal to 2.0.0.  The new packages should include the gdal_merge.py.  I realized they don't actually install the scripts in the setup.py.
