### ISSUE TITLE
conda-build needs setuptools?

### ISSUE THREAD

**Issue by WeatherGod** [conda/conda-recipes#236]
working from a fresh miniconda, I installed conda-build first and then proceeded to build the gdal package, and I ran into an error message stating that pkg_resources wasn't available. I installed setuptools and the build proceeded fine.

**Comment by ilanschnell** [comment]
pkg_resources is part of setuptools.  conda-build itself does not need setuptools, but if you create a recipe for packages which import pkg_resources, you have to add setuptools as a runtime dependency.

**Comment by WeatherGod** [comment]
you mean as a build dependency, not runtime (or maybe both?).

**Comment by ilanschnell** [comment]
I mean runtime, but this usually means both in the case of setuptools

**Comment by WeatherGod** [comment]
Ok, so this is an important note for PR #252

**Comment by asmeurer** [comment]
If the package imports it at runtime it has to be a runtime dependency.

**Comment by WeatherGod** [comment]
Yes, I understand that. The context here is that this happened during a
call to conda-*build*. I never saw gdal in the traceback (which I should
have posted), hence why I thought it was a conda-build problem.

I will try reproducing the problem tomorrow to see if adding setuptools as
a build dependency is sufficient.
