### ISSUE TITLE
gdal (gdalwarp), unable to load PROJ.4 library 

### ISSUE THREAD

**Issue by kpurdon** [conda/conda-recipes#305]
## Command:
```
gdalwarp -t_srs "EPSG:4326" /vagrant/arctic_natural_90m.tif /tmp/an90_geo2.tif
```
Note that this fails with any combo of EPSG codes or PROJ4 strings I enter and with many different files.

## Error:
```
ERROR 6: Unable to load PROJ.4 library (libproj.so), creation of
OGRCoordinateTransformation failed.
```

## Solution?
```
conda install -c osgeo proj4
```
After this install everything works, perhaps proj4 just needs to be added to the gdal `meta.yaml`?

### conda list (pre osgeo proj4 install)
```
# packages in environment at /opt/miniconda/envs/gdaltest:
#
curl                      7.38.0                        0    defaults
gdal                      1.11.2               np19py27_2    defaults
hdf5                      1.8.14                        0    defaults
libgdal                   1.11.2                        0    defaults
libnetcdf                 4.3.2                         1    defaults
numpy                     1.9.2                    py27_0    defaults
openssl                   1.0.1k                        1    <unknown>
pip                       6.1.1                    py27_0    defaults
python                    2.7.9                         3    <unknown>
readline                  6.2                           2    <unknown>
setuptools                15.2                     py27_0    defaults
sqlite                    3.8.4.1                       1    <unknown>
system                    5.8                           2    <unknown>
tk                        8.5.18                        0    <unknown>
zlib                      1.2.8                         0    <unknown>
```

### conda info
```
Current conda install:

             platform : linux-64
        conda version : 3.10.1
  conda-build version : 1.12.0
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : /opt/miniconda  (writable)
  default environment : /opt/miniconda/envs/gdaltest
     envs directories : /opt/miniconda/envs
        package cache : /opt/miniconda/pkgs
         channel URLs : https://conda.binstar.org/nsidc/channel/main/linux-64/
                        https://conda.binstar.org/nsidc/channel/main/noarch/
                        https://conda.binstar.org/nsidc/channel/dev/linux-64/
                        https://conda.binstar.org/nsidc/channel/dev/noarch/
                        http://snowhut.apps.int.nsidc.org/shares/export/sw/packages/python/conda/main/linux-64/
                        http://snowhut.apps.int.nsidc.org/shares/export/sw/packages/python/conda/main/noarch/
                        http://snowhut.apps.int.nsidc.org/shares/export/sw/packages/python/conda/dev/linux-64/
                        http://snowhut.apps.int.nsidc.org/shares/export/sw/packages/python/conda/dev/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/vagrant/.condarc
    is foreign system : False
```

**Comment by kpurdon** [comment]
@tswicegood I think this might be a minor change to the `meta.yaml` but I am still getting the build errors mentioned in your previous PR so I cannot easily test this.

**Comment by kpurdon** [comment]
## Possible Duplicate (Similar Issues):
https://github.com/ContinuumIO/anaconda-issues/issues/295
https://github.com/conda/conda-recipes/issues/263
https://github.com/conda/conda-recipes/issues/215
https://github.com/conda/conda-recipes/issues/211

**Comment by tswicegood** [comment]
cc @groutr

**Comment by RutgerK** [comment]
I just noticed something which might be related to these and other GDAL issues. I'm still working with GDAL 1.11.1 since #263 still is relevant for me.

Conda prepends a different folder to my PATH when activating the environment where GDAL is installed: `..\Miniconda\envs\my_env\Library\bin`

This folder contains the GDAL utilities, but is still missing some DLL's etc when compared to the `\osgeo\` folder in the `site_packages` from the same environment.

If during session (in a Python notebook), i change the system `PATH`, so it no longer first looks in the `\Library\` but in the `\osgeo\` folder, the `PROJ` related import errors disappear.

The idea of having using the utilities from the same GDAL build as the Python bindings is great, it avoids mixing multiple versions of GDAL. But apparently not all files needed are currently moved/copied to the `\Libray\` folder.

**Comment by michaelaye** [comment]
The osgeo install does not solve my problem (Using Python 3 with conda). Currently, proj4 4.9.1 is being installed but the libproj is still not being found during projection related tasks.

**Comment by mhearne-usgs** [comment]
I get this error on Mac OS 
Anaconda version: Python 3.5.1 |Anaconda 2.4.1 (x86_64)| (default, Dec  7 2015, 11:24:55)

Here's the output of conda list gdal:

gdal                      2.0.0               np110py35_0
libgdal                   2.0.0                         0

**Comment by michaelaye** [comment]
I had to use homebrew's PROJ4 (or was it homebrew's GDAL?) to make things work for me.

**Comment by michaelaye** [comment]
What's the fix?

**Comment by kpurdon** [comment]
@michaelaye cleaning out issues (that I created) ... nobody is assigned to this and or working on it. I've moved on to other things long ago.... feel free to create a new issue and reference this one if it's still an issue for you.

**Comment by msarahan** [comment]
Should you choose to raise a new issue, please do so at conda-forge: https://github.com/conda-forge/gdal-feedstock .  It has superseded conda-recipes as the community hub for these recipes.
