### ISSUE TITLE
Help with environment variables in OpenBabel recipe

### ISSUE THREAD

**Issue by rwest** [conda/conda-recipes#309]
I'm working on a conda-build recipe for OpenBabel,
https://github.com/GreenGroup/conda-recipes/tree/openbabel/openbabel

I've got quite far - it can build the dependencies and the software itself, but when it comes to runtime, the software looks first in `$BABEL_LIBDIR` (and I think then in `/usr/local/lib/openbabel/`) for a bunch of its libraries, and similarly for `$BABEL_DATADIR` (which it expects to be `/usr/local/share/openbabel`) for some data that comes with it.

The following text is from http://open-babel.readthedocs.org/en/latest/Installation/install.html#troubleshooting-build-problems 
> BABEL_LIBDIR - Used to find plugins such as the file formats
If obabel -L formats does not list any file formats, then you need to set this environment variable to the directory where the file formats were installed, typically /usr/local/lib/openbabel/.
> BABEL_DATADIR - Used to find the location of the data files used for fingerprints, forcefields, etc.
If you get errors about not being able to find some .txt files, then you should set this to the name of the folder containing files such as patterns.txt and MACCS.txt. These are typically installed to /usr/local/share/openbabel.

If I manually `export BABEL_LIBDIR=/Users/rwest/anaconda/envs/_test/lib/openbabel/2.3.2` then I can get things to function, but that makes it rather cumbersome to use.

How should I go about fixing this? Can I somehow set the $BABEL_LIBDIR and $BABEL_DATADIR whenever the conda environment is activated? Or do we need to modify the source code so it looks somewhere else for these things? Any advice would be greatly appreciated.

(As well as the conda-recipe experts, I wonder if OpenBabel folks like @ghutchis and @baoilleach will have any ideas...?)

**Comment by ccordoba12** [comment]
> Can I somehow set the $BABEL_LIBDIR and $BABEL_DATADIR whenever the conda environment is activated?

Yes, look at [conda env](https://github.com/conda/conda-env). The documentation is sparse, but basically you need to add bash scripts that will be ran after activation. Take a look at the gdal recipe here to see how it works.

> Or do we need to modify the source code so it looks somewhere else for these things?

Well, you need to do that if you want for OpenBabel to work on the root environment. Please take a look at how we do this in the freetype recipe.

**Comment by rwest** [comment]
Thanks for the tips! The gdal recipe is helpful, but ideally I'd like something that can work in the root environment (I'm unsure why a similar approach won't work - isn't the root environment also activated? Anyway, that's an aside).  But I couldn't see what you're referring to in the freetype recipe; what should I be looking for?

**Comment by ccordoba12** [comment]
> isn't the root environment also activated?

Yep, that's the problem: the root environment is not activated.

> But I couldn't see what you're referring to in the freetype recipe; what should I be looking for?

Sorry, it's the fontconfig recipe, specifically to the `fcf.patch` file. There we replaced the `FONTCONFIG_FILE` env var for variable that we could later replace when installing the package.

**Comment by rwest** [comment]
Thanks, that helped. 
Poking around the source I saw that the cmake recipe is actually translating `src/config.h.cmake` --> `/include/openbabel/babelconfig.h` and putting in the correct (build time) `$PREFIX`-based paths, 
```
#define BABEL_DATADIR "/Users/rwest/anaconda/envs/_build/share/openbabel"
#define OB_MODULE_PATH "/Users/rwest/anaconda/envs/_build/lib/openbabel/2.3.2"
```
which then get built in to most of the libraries, so the patch shouldn't be needed.

Some more reading of the [conda build Recipe Reference](http://conda.pydata.org/docs/build.html) and I realized that `detect_binary_files_with_prefix` defaults to `false`, so I tried again with 
```
build:
    detect_binary_files_with_prefix: true
```
in my `meta.yaml` and it seems to have worked :grinning:

A few unit tests, and I think I'll have a functioning recipe (for unix).

**Comment by ccordoba12** [comment]
Great!! Feel free to close this issue when you have a working recipe (hopefully submitted here too ;-)

**Comment by rwest** [comment]
Recipe submitted in https://github.com/conda/conda-recipes/pull/310
(not yet tested on linux though ought to work, and definitely not yet working for windows, but it's a start)
