### ISSUE TITLE
allow pip dependencies in a conda recipe's meta.yaml

### ISSUE THREAD

**Issue by JeremyEnns** [conda/conda-recipes#317]
It would be great if you could define pip dependencies in a conda recipe's meta.yaml in the same way you can for an environment.yaml exported with 'conda env export'

Example: 
... 
requirements: 
build: 
- python 
- pip: 
- loweb

**Comment by JeremyEnns** [comment]
Can you tag this as a feature request

**Comment by jf---** [comment]
:+1:

**Comment by hargup** [comment]
@JeremyEnns @jf--- can you explain what do you mean by "pip dependencies" and your use case. Do want the want the packages not available with conda to marked as "pip dependencies".

**Comment by jakirkham** [comment]
This issue seems like something that belongs elsewhere ( https://github.com/conda/conda-build/issues ).

**Comment by telson** [comment]
:+1:

**Comment by jakirkham** [comment]
Yeah, this is a dup of this issue ( https://github.com/conda/conda/issues/931 ). We should close this and track over there.

**Comment by ccordoba12** [comment]
Ok, thanks @jakirkham. Closing then :-)
