### ISSUE TITLE
pyqt comes with no support for scintilla

### ISSUE THREAD

**Issue by jf---** [conda/conda-recipes#322]
```python
 from PyQt4 import Qsci
ImportError: cannot import name Qsci
```

for instance, [enaml's live editor ( 23:22) ](https://vimeo.com/79536617) relies on this, as does traits IIRC

**Comment by ccordoba12** [comment]
QScintilla is propietary, I'm afraid. The only platform where QScintilla is supported is Windows because we're paying support to Riverbank for it.

Sorry, there's nothing else we can do about it.

**Comment by jf---** [comment]
Fair point! Thanks for the heads up....
