### ISSUE TITLE
New version of PyTables breaks GDAL Links to libhdf

### ISSUE THREAD

**Issue by venabled** [conda/conda-recipes#344]
The current versions of pytables (3.2.0) updates libhdf5 (1.8.14-14 --> 1.8.15.1-1), which then breaks the linking for libgdal: 

`dlopen(/Users/xxx/anaconda/lib/python2.7/site-packages/osgeo/_gdal.so, 2): Library not loaded: @rpath/./libhdf5_hl.9.dylib
  Referenced from: /Users/venabled/anaconda/lib/libgdal.1.dylib
  Reason: image not found`

Probably just need to rebuild gdal against the newer version of HDF5 / fix how it links to a versioned number of hdf5.

**Comment by asmeurer** [comment]
@groutr

**Comment by groutr** [comment]
Already on it :)

**Comment by venabled** [comment]
@asmeurer @groutr you guys are awesome. Is this the right place to post issues like this?

**Comment by groutr** [comment]
It is one place.  I check https://github.com/ContinuumIO/anaconda-issues/issues more frequently for issues relating to official anaconda packages.

**Comment by groutr** [comment]
These packages have been updated.  Is this still an issue?

**Comment by venabled** [comment]
It appears gdal is still trying to downgrade hdf5: 

```
levin:bin venabled$ conda install gdal
Fetching package metadata: ..........
Solving package specifications: .
Package plan for installation in environment /Users/venabled/anaconda:

The following NEW packages will be INSTALLED:

    gdal: 1.11.2-np19py27_14

The following packages will be DOWNGRADED:

    hdf5: 1.8.15.1-1 --> 1.8.14-14    
```

Is there a specific channel/package I should be looking for? The current ones on binstar for anaconda distribution show that the files haven't been changed in 1-2 months: 

https://binstar.org/anaconda/gdal/files

**Comment by groutr** [comment]
what is the output of `cona info`?

**Comment by venabled** [comment]
```
levin:bin venabled$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.14.1
  conda-build version : 1.11.0
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /Users/venabled/anaconda  (writable)
  default environment : /Users/venabled/anaconda
     envs directories : /Users/venabled/anaconda/envs
        package cache : /Users/venabled/anaconda/pkgs
         channel URLs : https://conda.binstar.org/menpo/osx-64/
                        https://conda.binstar.org/menpo/noarch/
                        http://conda.binstar.org/osgeo/osx-64/
                        http://conda.binstar.org/osgeo/noarch/
                        http://conda.binstar.org/sgillies/osx-64/
                        http://conda.binstar.org/sgillies/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/venabled/.condarc
    is foreign system : False
```

**Comment by venabled** [comment]
Must be an issue with osx-64, as my linux-64 install works fine.

**Comment by groutr** [comment]
I think the gdal package you are grabbing is not from repo.continuum.io.  I just updated libgdal/gdal to 2.0.0 this morning which should definitely fix this issue.

**Comment by venabled** [comment]
Thanks for the help! I had an issue where even after telling it to install from a different channel, if the file name was the same it just unzipped the cached package in ```~/anaconda/pkgs```. Manually deleting gdal/libnetcdf related packages worked.
