### ISSUE TITLE
[cmake] fails at startup on OS X 10.6 with "dyld: Symbol not found: _kSecImportExportPassphrase"

### ISSUE THREAD

**Issue by benmwebb** [conda/conda-recipes#368]
(Not sure if this is the right place to report this, since the cmake package here is 3.2.2 but the one that `conda` installs is 3.2.3. If not the right place, where is?)

On an OS X 10.6 machine, cmake doesn't work:

    $ conda install cmake
    [...]
    $ cmake
    dyld: Symbol not found: _kSecImportExportPassphrase
      Referenced from: /tmp/conda.3093/bin/cmake
      Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
     in /tmp/conda.3093/bin/cmake
    Trace/BPT trap

Looks like the cmake package just needs to be rebuilt on a 10.6 (or older?) Mac.

BTW, if 10.6 isn't supported, the Anaconda quickstart guide (or similar) should probably say what the minimum OS X supported version is - all I could find for OSX under system requirements is "64-bit Intel processor" (and miniconda itself installs and runs just fine on a 10.6 machine). I personally use 10.10 but try to build my own conda packages on the oldest OS X I have available to maximize compatibility (but can't do this right now since cmake doesn't work ;) Similarly I build Linux packages on RHEL 5.

**Comment by benmwebb** [comment]
I see from [the conda docs](http://conda.pydata.org/docs/building/environment-vars.html) that `MACOSX_DEPLOYMENT_TARGET` is set to `10.6`, so I guess 10.6 *is* your floor. So presumably either this is getting unset somehow when the cmake package is built, or Apple broke something.

Anyway, I rebuilt the cmake package on a 10.6 system and the resulting `cmake` binary works fine for me. Feel free to compare yours with that at https://anaconda.org/salilab/cmake-mac.

**Comment by ccordoba12** [comment]
Let's close this one in favor of the issue posted in `anaconda-issues`
