### ISSUE TITLE
[vtk][osx] VTKTargets.cmake has hard references to OSX 10.7 SDK

### ISSUE THREAD

**Issue by julienr** [conda/conda-recipes#509]
I was trying to build the PCL (pointclouds.org) library in my conda env (so using conda-provided VTK) on OSX 10.9 with XCode 5.
I ran into errors with the linker complaining that it couldn't find the AGL.framework :
````
error: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/System/Library/Frameworks/AGL.framework', needed by 'lib/libpcl_io.1.
8.0.dylib', missing and no known rule to make it
```
It turns out that XCode 5 doesn't have the SDK for MacOSX10.7. Running a `cmake --trace`, I found out that this path comes from conda's VTK (`lib/cmake/vtk-6.3/VTKTargets.cmake`), which has this on line 602
````
set_target_properties(vtkRenderingOpenGL PROPERTIES
  INTERFACE_LINK_LIBRARIES "vtkRenderingCore;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/System/Library/Frameworks/AGL.framework;/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/System/Library/Frameworks/OpenGL.framework;-framework Cocoa"
)
```
but I think it should look like
```
  INTERFACE_LINK_LIBRARIES "vtkRenderingCore;-framework AGL;-framework OpenGL;-framework Cocoa"
```
Replacing the full path to the frameworks with `-framework OpenGL` and `-framework AGL` on lines 602, 617 and 196 seems to have solved the problem.

**Comment by ccordoba12** [comment]
I'm sorry, but this is not our fault. We just compile the VTK source code provided by Kitware without any further changes.

So I think you need to report this problem with the VTK developers to see what they think about it.

**Comment by julienr** [comment]
Thanks for your response.
The problem is due to the fact that (I think) the conda package is compiled on OSX 10.7 but is then distributed as being compatible with any version of OSX, which it isn't really (or well, it is as long as you don't try to link against it). Would there be any way to have different packages for different OSX versions ?

If you still think this is a VTK problem, I'll try to contact the VTK developers.

**Comment by ccordoba12** [comment]
> the conda package is compiled on OSX 10.7

Yep, that's the case :-) We do that ensure that our packages work on 10.7 or older.

> but is then distributed as being compatible with any version of OSX,  with any version of OSX, which it isn't really (or well, it is as long as you don't try to link against it).

Well, the package works correctly on any version equal or older than 10.7. And you should be able to link against it if you have installed the 10.7 SDK (at least that's what I understand from your previous posts).

For that (I think) you can install an older XCode version, extract the SDK from it and install it. I know that's too much work, but I don't know how else we could improve the situation.

> Would there be any way to have different packages for different OSX versions ?

Sorry, conda is not able to differentiate between OS X versions.

**Comment by jf---** [comment]
@julienr , here is a [GH repo](https://github.com/phracker/MacOSX-SDKs/releases) where the osx SDK's can be downloaded... pretty useful...

**Comment by julienr** [comment]
Thank you for your answers. It indeed seems like something that should be fixed in VTK.
In the meantime, I'll just download the 10.7 SDK as proposed by @jf

**Comment by ccordoba12** [comment]
Thanks @julienr for understanding :-)

**Comment by jf** [comment]
hi @julienr quick tip: the *tab* autocompletes (and not the *spacebar*). This has nothing to do with me, and while it might be interesting to occasionally stumble across the interesting project, I would prefer not to be pulled in to a conversation in this way.

(hi Jelle! :} We meet again (formerly https://github.com/Anaconda-Server/anaconda-build/issues/20#issuecomment-155991829; now edited by @srossross after I pointed out the mistake (let me just for the record say since I didn't get the chance to: "Ok. Pls don't do it again.")).
