### ISSUE TITLE
scrappy: Error: bad character '-' in package/version: 0.2.10-beta-11

### ISSUE THREAD

**Issue by wojdyr** [conda/conda-recipes#514]
scrappy formula has wrong (old-style?) version number

```
Removing old build environment
Removing old work directory
Error: bad character '-' in package/version: 0.2.10-beta-11
```

**Comment by ilanschnell** [comment]
Thanks for reporting the issue.  Just fixed it: https://github.com/conda/conda-recipes/commit/b183bc781c280111cabe52420a6b256b22e1f23b
