### ISSUE TITLE
pysam recipe

### ISSUE THREAD

**Issue by tiagoantao** [conda/conda-recipes#531]
The pysam recipe is quite old and such oldness deleterious in some environments. Two suggestions:

1. Update it

OR

2. Delete it altogether as the bioconda project https://bioconda.github.io/ has this covered

**Comment by msarahan** [comment]
Pull requests are welcome. Conda-recipes is meant to be a community maintained recipe collection (not a package repository).  If this package is out of date in the conda package repository, please file an issue at https://github.com/ContinuumIO/anaconda-issues
