### ISSUE TITLE
hdf4 not built for all versions of Visual Studio on Windows

### ISSUE THREAD

**Issue by gillins** [conda/conda-recipes#568]
Appears to be built with VS 2008, but needs to be available in all VC versions using the vc9, vc10 and vc14 features. See the hdf5 build.

hdf4 is used by GDAL so needs to be available in all variants so the correct one can be selected depending on the build on GDAL which in turn is dictated by the Python version.

Recipe not available on github (see #567), so attached patch should fix issue with VS2015.
[HDFTests.c.patch.txt](https://github.com/conda/conda-recipes/files/107715/HDFTests.c.patch.txt)

**Comment by RutgerK** [comment]
Does this patch fix the crashing of CMake? Frustrated by the available GDAL packages (no JPEG2000 support for example) i attempted to build it myself with VS2015. One problem i encountered was a crash when running CMake for HDF4 version 2.11.

**Comment by gillins** [comment]
Yes it does. We are attempting to improve the supplied GDAL, especially on Windows.

**Comment by gillins** [comment]
Now available under conda-forge
