### ISSUE TITLE
activate script sets wrong GDAL_DATA path

### ISSUE THREAD

**Issue by RutgerK** [conda/conda-recipes#591]
The more recent `GDAL` packages set the GDAL_DATA environment variable by using the `gdal-activate.bat` script in the `\envs\myenv\etc\conda\activate.d` folder. 

For my version the path is wrongly defined in the bat-file. It moves one directory to far upwards i think, there shouldn't be a backslash after the variable for the current working dir (`%~dp0`).  

It sets the following path:
`set GDAL_DATA="%~dp0\..\..\..\Library\share\gdal"` 

And, at least for me, it should be:
`set GDAL_DATA="%~dp0..\..\..\Library\share\gdal"`

I'm using this package:
`https://repo.continuum.io/pkgs/free/win-64/gdal-2.0.0-py34_1.tar.bz2`

edit: I Initially said it went too little 'upwards', its was something different

**Comment by RutgerK** [comment]
It seems like it sets the path correct, but it its lost again after the environment is activated. This is already discussed at:
https://github.com/conda/conda-env/pull/219

Sorry for the confusion, my bad.

**Comment by msarahan** [comment]
Thanks for the reminder. We'll try to get this fixed soon.

**Comment by RutgerK** [comment]
Thanks, msarahan. Its appreciated!

In the mean time, in case any one is interested in a python workaround, this is how you can set the `GDAL_DATA` path from within python. But modifying `(de)activate.bat` accordingly as in the PR is probably more convenient.

```Python
import os
import gdal

gdal_data_dir = os.path.join(os.path.dirname(gdal.__file__), '..\..\Library\share\gdal')

os.environ['GDAL_DATA'] = os.path.normpath(gdal_data_dir)
```

But note that the scope is not identical, i think changing it from within Python makes it last only while the same process (python.exe) is running, and is only set for things running from that process.
