### ISSUE TITLE
r 3.2.3?

### ISSUE THREAD

**Issue by lendle** [conda/conda-recipes#615]
The current r-base conda recipe is for R 3.2.2: https://github.com/conda/conda-recipes/blob/master/r-base/meta.yaml. 3.2.3 was released in December. Is there plans to upgrade this any time soon?

For what it's worth, 3.2.4 is scheduled to be released in a couple of weeks.

**Comment by mingwandroid** [comment]
`R 3.3.1` is available on https://anaconda.org/rdonnellyr if you'd like to test it.
