### ISSUE TITLE
libgd: cmake installation broken

### ISSUE THREAD

**Issue by croth1** [conda/conda-recipes#625]
Conda's recipe for libgd uses the cmake build systems from the git repository. This however seems to be buggy.

The binary `gdlib-config` is not installed, which breaks configuration scripts that use it. I see problems when trying to build gnuplot.

See also https://github.com/libgd/libgd/issues/164. Would it be possible to go back to the old `autotools` configuration until these bugs are fixed?

The libgd version I introduced in my pull request below, seems to work. However it is shadowed by the faulty version from the defaults repository. 

https://github.com/bioconda/bioconda-recipes/pull/924

**Comment by groutr** [comment]
How are your channels set up in .condarc?  Are you building with `conda build -c bioconda ...`?  If you've already build libgd locally, that will take precedence (conda build automatically prepends the local build directory).

**Comment by croth1** [comment]
libgd at conda-forge is up-to-date - closing this one.
