### ISSUE TITLE
r-mro should depend on xz

### ISSUE THREAD

**Issue by timsnyder** [conda/conda-recipes#634]
When I installed r-mro following the doc (I added mro before r in my channels list), on RedHat 6.5, I got runtime link failures looking for liblzma.so:
` 
% R
$PREFIX/lib/R/bin/exec/R: error while loading shared libraries: liblzma.so.5: cannot open shared object file: No such file or directory
 `

After installing the xz package from defaults, the dynamic linking problem was solved.  @electronwill and @groutr, since xz in the defaults channel can satisfy this dep, should we add it to the runtime requirements?

**Comment by timsnyder** [comment]
Actually, I think that r-mro has xz satisfied transitively when installed into a clean environment.

I initially added r-mro to an existing environment with many packages in it that were pinned and only saw:
> The following NEW packages will be INSTALLED:
>
>    glib:        2.43.0-2 r
>    harfbuzz:    0.9.39-0 defaults
>    libffi:      3.0.13-3 asmeurer
>    libgcc:      4.8.5-1  defaults
>    libgfortran: 3.0-0    defaults
>    pango:       1.39.0-0 defaults
>    r:           3.2.3-0  mro

But if I create a brand new environment to install mro and only use defaults,mro and r channels, I see xz being installed:

> % conda create --override-channels -c defaults -c mro -c r -n mro-test r
> Using Anaconda Cloud api site https://api.anaconda.org
> Fetching package metadata: ........
> Solving package specifications: ..........
> 
> Package plan for installation in environment $PREFIX:
> 
> The following NEW packages will be INSTALLED:
> 
>     cairo:       1.12.18-6 defaults
>     fontconfig:  2.11.1-5  defaults
>     freetype:    2.5.5-0   defaults
>     glib:        2.43.0-2  r
>     harfbuzz:    0.9.39-0  defaults
>     icu:         54.1-0    defaults
>     jbig:        2.1-0     defaults
>     jpeg:        8d-0      defaults
>     libffi:      3.0.13-0  defaults (soft-link)
>     libgcc:      4.8.5-1   defaults
>     libgfortran: 3.0-0     defaults (soft-link)
>     libpng:      1.6.17-0  defaults
>     libtiff:     4.0.6-1   defaults
>     libxml2:     2.9.2-0   defaults
>     pango:       1.39.0-0  defaults
>     pixman:      0.32.6-0  defaults
>     r:           3.2.3-0   mro      (soft-link)
>     readline:    6.2-2     defaults (soft-link)
>     xz:          5.0.5-1   defaults (soft-link)
>     zlib:        1.2.8-0   defaults

This seems like user-error or a personal issue and not something that needs to be addressed in the recipe.  I should probably figure out which of my pinned libs are old relative to what a clean install would have but I won't bore you guys with that detail.

**Comment by timsnyder** [comment]
It was that I had 'libtiff 4.0.2 1' pinned and installed from defaults in my initial env.  Sorry for the SPAM ticket.

**Comment by electronwill** [comment]
Not a problem. Glad to see you found the answer!
