### ISSUE TITLE
r-boot md5 mismatch

### ISSUE THREAD

**Issue by daler** [conda/conda-recipes#637]
Hi - 

On three separate machines today (all on different networks to rule out strange network issues) I'm getting an md5sum mismatch on at least one R package. The command:

```
conda install -n tmp --channel=r r-boot
```

exits with the error:

```
Error: MD5 sums mismatch for download: https://conda.anaconda.org/t/da-13b98bfe-9a00-481f-b163-c5b442f745b4/r/linux-64/r-boot-1.3_17-r3.2.2_0.tar.bz2
(210ce863c3d426eaf6111d14721a2dbe != 7cc08052f9d5ba6b131d8b3b6d915c77)
```

On anaconda.org, it looks like this package hasn't been touched in 6 months. Any ideas?

**Comment by groutr** [comment]
This is being sorted out right now.  It should be fixed by the end of today.

**Comment by daler** [comment]
Seems to be working now, thanks!
