### ISSUE TITLE
qt4 build recipe - incorrect library path being set OS X

### ISSUE THREAD

**Issue by mgrady3** [conda/conda-recipes#672]
With a fresh conda env with python 2.7 or 3.5 I find an issue with the Qt4/PyQt4 installation as follows:

opening and interpreter and executing the following gives a strange result:

    
    from PyQt4.QtCore import QLibraryInfo
    print(str(QLibraryInfo.location(QLibraryInfo.LibrariesPath)))
    

For me this prints out: 

    '/Users/felipe/miniconda/envs/_build/lib'

This is interesting for two reasons:
 
 A. I am not felipe
 B. I am not using miniconda

What I believe is going on, though I may be incorrect, is that in the conda qt build recipe, the $PREFIX environment variable is not being set correctly. This variable gets prepended to each of the paths which can be found in the enum QLibraryInfo.LibraryLocation. 

This does not appear to be a major problem until some external program goes looking for an exact path as specified by the output of QLibraryInfo.LibraryLocation or one of the other values in the enum.

I ran into an issue using pyinstaller to package a PyQt4 application. It tries to track down the exact path to a file qt_menu.nib, and fails because the username provided in the path from QLibraryInfo.LibraryLocation is incorrect.

This testing was done on OS X.11.4, conda 4.0.5, with Qt4 and PyQt4.

**Comment by mgrady3** [comment]
After an afternoon of deliberation, I'm realizing that this is most likely not an issue with conda nor the conda build command.

Rather, it seems that if the enum QLibraryInfo is set according to the build environment, then programs should not query this variable for a valid path to Qt libraries as its possible the Qt framework was built on a separate machine and not on the local machine. You can close this issue if this is the case.

**Comment by ccordoba12** [comment]
Yes, you should use `qmake -query` to get the right Qt paths in your current conda environment :-)
