### ISSUE TITLE
pyqt build is not working

### ISSUE THREAD

**Issue by peter1000** [conda/conda-recipes#84]
just to let you know:

the pyqt recipe creates things under: /opt/anaconda1anaconda2anaconda3
Linux debian wheezy: linux linux-6 and later can not find it: maybe the link should be made somewhere below _build or env?

```
BUILD START: pyqt-4.10.3-py33_0
Source cache directory is: /home/workerm/miniconda3/conda-bld/src_cache
Found source in cache: PyQt-x11-gpl-4.10.3.tar.gz
Applying patch: '/home/workerm/miniconda3/conda-recipes-master/pyqt/configure.patch'
patching file configure.py
source tree in: /home/workerm/miniconda3/conda-bld/work/PyQt-x11-gpl-4.10.3
++ uname
+ '[' Linux == Darwin ']'
+ export QMAKESPEC=linux-g++
+ QMAKESPEC=linux-g++
+ sudo mkdir -p /opt/anaconda1anaconda2anaconda3/
+ sudo chmod 777 /opt/anaconda1anaconda2anaconda3
+ ln -s /home/workerm/miniconda3/envs/_build/mkspecs /opt/anaconda1anaconda2anaconda3/mkspecs
+ ln -s /home/workerm/miniconda3/envs/_build/include /opt/anaconda1anaconda2anaconda3/include
+ ln -s /home/workerm/miniconda3/envs/_build/lib /opt/anaconda1anaconda2anaconda3/lib
+ ln -s /home/workerm/miniconda3/envs/_build/bin /opt/anaconda1anaconda2anaconda3/bin
+ /home/workerm/miniconda3/envs/_build/bin/python configure-ng.py --verbose --confirm-license --bindir=/home/workerm/miniconda3/envs/_build/bin --destdir=/home/workerm/miniconda3/envs/_build/lib/python3.3/site-packages
Querying qmake about your Qt installation...
Determining the details of your Qt installation...
/home/workerm/miniconda3/envs/_build/bin/qmake -o qtdetail.mk qtdetail.pro
Could not find mkspecs for your QMAKESPEC(linux-g++) after trying:
	/opt/anaconda1anaconda2anaconda3/mkspecs
Error processing project file: qtdetail.pro
Error: Failed to determine the detail of your Qt installation. Try again using
the --verbose flag to see more detail about the problem.
Command failed: /bin/bash -x -e /home/workerm/miniconda3/conda-recipes-master/pyqt/build.sh

```

**Comment by hargup** [comment]
This issue also creates problem with `gem` installation of `capybara-webkit`. See https://github.com/thoughtbot/capybara-webkit/issues/627

**Comment by ccordoba12** [comment]
I'm working right now to create a working PyQt4 recipe that can be used by other projects too.

**Comment by ccordoba12** [comment]
This was fixed in revision 90b9ffe, by preventing the Qt recipe to remove the `mkspecs` dir

**Comment by ccordoba12** [comment]
This was definitely fixed in revision 2cf9167, by removing the hack involving `/opt/anaconda1anaconda2anaconda3`.

**Comment by asmeurer** [comment]
FYI stuff using `/opt/anaconda1anaconda2anaconda3` is not a hack. Conda build puts those files in has_prefix, and conda replaces the paths with the install prefix. See http://conda.pydata.org/docs/spec.html.

**Comment by ccordoba12** [comment]
Sorry, I thought it was because I haven't encountered so far. I also thought it was needed by the internal build system and not by conda-build.

**Comment by asmeurer** [comment]
The origin of it is that it is the prefix used in the internal build system, but it is also recognized by conda and conda-build. 

For conda-build, however, it is typically cleaner to use the build prefix when possible (`$PREFIX`), as that's less confusing than `/opt/anaconda1anaconda2anaconda3`. But the final result is the same.

**Comment by ccordoba12** [comment]
Ok, thanks for the clarification @asmeurer :-)
